apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-acs-lpsre-admins-project
rules:
# LP SRE can interact with ACS
- apiGroups:
  - platform.stackrox.io
  resources:
  - centrals
  - securedclusters
  verbs:
  - get
  - list
  - watch
  - patch
# LP SRE can get pod logs
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - watch
# LP SRE can delete pods
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
# LP SRE can run commands in pods
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
# LP SRE can restart deployments/statefulsets/deploymentconfigs
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - patch
# LP SRE can scale deployments
- apiGroups:
  - apps
  resources:
  - deployments/scale
  verbs:
  - patch