apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-lpsre-opentelemetry
  namespace: openshift-opentelemetry-operator
rules:
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetrycollectors
  verbs:
  - list
  - get
  - watch
