apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-sre-token-replacer
  namespace: openshift-sre-token-scraper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-sre-token-replacer
subjects:
  - kind: ServiceAccount
    name: openshift-sre-token-scraper
    namespace: openshift-sre-token-scraper
