apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-sre-token-replacer
  namespace: openshift-sre-token-scraper
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - patch
