deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: In
      values: ["4.13","4.14"]
    - key: hive.openshift.io/version-major-minor-patch
      operator: NotIn
      values: ["4.13.0","4.13.1","4.13.2","4.13.3"]
    - key: api.openshift.com/legal-entity-id
      operator: In
      values: "${{LOG_LINKING_ENTITY_IDS}}"
