apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dedicated-admins-cert-secret
  namespace: openshift-kube-apiserver-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - patch
  resourceNames:
  - kube-apiserver-to-kubelet-signer
