apiVersion: batch/v1
kind: Job
metadata:
    name: osd-cluster-ready
    namespace: openshift-monitoring
spec:
    # NOTE: We're making this ridiculously high to ensure that the
    # actual code gets a chance to run to completion. However, consumers
    # should implement a sensible timeout rather than waiting forever.
    backoffLimit: 500
    template:
        metadata:
            name: osd-cluster-ready
            labels:
                # Keep this in sync with image
                managed.openshift.io/version: "v0.1.66-bb79af5"
        spec:
            containers:
            - name: osd-cluster-ready
              # Keep the `managed.openshift.io/version` label in sync
              # with this
              image: "quay.io/openshift-sre/osd-cluster-ready@sha256:84d0c91e5df7455f164eb6cc5544a09e271e94e5c7d0a7644332de69127c8437"
              command: ["/root/main"]
            restartPolicy: OnFailure
            serviceAccountName: osd-cluster-ready
