deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchLabels:
    api.openshift.com/addon-managed-odh: "true"
    api.openshift.com/addon-ocs-consumer: "true"
    api.openshift.com/addon-ocs-converged: "true"
    api.openshift.com/addon-ocs-provider: "true"
    api.openshift.com/addon-reference-addon: "true"
  matchLabelsApplyMode: "OR"
