deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: In
      values: ["4.8", "4.9"]
    - key: api.openshift.com/legal-entity-id
      operator: In
      values: ["${{DPTP_LEGAL_ENTITY_ID}}"]
