apiVersion: apps/v1
kind: DaemonSet
name: node-ca
namespace: openshift-image-registry
applyMode: AlwaysApply
# https://bugzilla.redhat.com/show_bug.cgi?id=1915081#c3
patch: '{"spec":{"template":{"spec":{"tolerations":[{"operator":"Exists"}]}}}}'
patchType: merge
