apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-devaccess
  namespace: openshift-must-gather-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - managed.openshift.io
  resources:
  - mustgathers
  verbs:
  - '*'
