apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: 5min-object-backup
  namespace: openshift-velero
spec:
  schedule: '*/5 * * * *'
  template:
    includedNamespaces:
    - '*'
    excludedResources:
    - imagetags
    - images
    - templateinstances
    - clusterserviceversions
    - packagemanifests
    - subscriptions
    - servicebrokers
    - servicebindings
    - serviceclasses
    - serviceinstances
    - serviceplans
    - operatorgroups
    - events
    snapshotVolumes: false
    ttl: 0h25m0s
