deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
  # This will be removed once SDE-2149 has been completed
  - key: hive.openshift.io/version-major-minor
    operator: In
    values:
      - "4.12"
      - "4.13"
      - "4.14"
      - "4.15"
  - key: ext-hypershift.openshift.io/cluster-type
    operator: NotIn
    values: ["management-cluster"]
