apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-full-backup
  namespace: openshift-velero
spec:
  schedule: 0 1 * * *
  template:
    includedNamespaces:
    - '*'
    excludedResources:
    - imagetags
    - images
    - templateinstances
    - clusterserviceversions
    - packagemanifests
    - subscriptions
    - servicebrokers
    - servicebindings
    - serviceclasses
    - serviceinstances
    - serviceplans
    - operatorgroups
    - events
    ttl: 168h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-object-backup
  namespace: openshift-velero
spec:
  schedule: 17 * * * *
  template:
    includedNamespaces:
    - '*'
    excludedResources:
    - imagetags
    - images
    - templateinstances
    - clusterserviceversions
    - packagemanifests
    - subscriptions
    - servicebrokers
    - servicebindings
    - serviceclasses
    - serviceinstances
    - serviceplans
    - operatorgroups
    - events
    snapshotVolumes: false
    ttl: 24h0m0s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: weekly-full-backup
  namespace: openshift-velero
spec:
  schedule: 0 2 * * 1
  template:
    includedNamespaces:
    - '*'
    excludedResources:
    - imagetags
    - images
    - templateinstances
    - clusterserviceversions
    - packagemanifests
    - subscriptions
    - servicebrokers
    - servicebindings
    - serviceclasses
    - serviceinstances
    - serviceplans
    - operatorgroups
    - events
    ttl: 720h0m0s
