apiVersion: v1
kind: ServiceAccount
metadata:
  name: osd-delete-backplane-serviceaccounts
  namespace: openshift-backplane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osd-delete-backplane-serviceaccounts
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osd-get-namespace
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
---
apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: osd-delete-backplane-serviceaccounts
  namespace: openshift-rbac-permissions
spec:
  clusterPermissions:
    - osd-get-namespace
  permissions:
    - allowFirst: true
      clusterRoleName: osd-delete-backplane-serviceaccounts
      namespacesAllowedRegex: "(^openshift-backplane-.*)"
  subjectKind: User
  subjectName: system:serviceaccount:openshift-backplane:osd-delete-backplane-serviceaccounts