apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backplane-cee-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backplane-cee-cluster-readers
subjects:
- kind: Group
  name: system:serviceaccounts:openshift-backplane-cee
