deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  # if we ever remove this, do not remove the resources
  resourceApplyMode: "Upsert"
  # if ANY of the conditions are met, apply this SSS
  matchLabelsApplyMode: "OR"
  matchExpressions:
  # Ensure SRE does not get alerts for in-cluster logging on ROSA clusters
  # https://issues.redhat.com/browse/OSD-6322
  - key: api.openshift.com/product
    operator: In
    values: ["rosa"]

  # Disable routing in-cluster logging alerts to SRE PD for OCP 4.7+
  # https://issues.redhat.com/browse/OSD-6324
  - key: hive.openshift.io/version-major-minor
    operator: NotIn
    values: ["4.4","4.5","4.6"]
