deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  # If this object is deleted, it'll cause a reboot. As such, only Upsert this object.
  resourceApplyMode: Upsert
  matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: NotIn
      values: ["4.1", "4.2", "4.3", "4.4", "4.5", "4.6", "4.7"]
    - key: hive.openshift.io/version-major-minor-patch
      operator: NotIn
      values:
      - 4.8.2
      - 4.8.3
      - 4.8.4
      - 4.8.5
      - 4.8.9
      - 4.8.10
      - 4.8.11
      - 4.8.12
      - 4.8.13
      - 4.8.14
      - 4.8.15
      - 4.8.17
      - 4.8.18
      - 4.8.19
      - 4.8.20
      - 4.8.21
      - 4.8.22
      - 4.8.23
      - 4.8.24
      - 4.8.25
      - 4.8.26
      - 4.8.27
      - 4.8.28
      - 4.8.29
      - 4.8.31
      - 4.8.32
      - 4.8.33
      - 4.8.34
      - 4.9.0
      - 4.9.4
      - 4.9.5
      - 4.9.6
      - 4.9.7
      - 4.9.8
      - 4.9.9
      - 4.9.10
      - 4.9.11
      - 4.9.12
      - 4.9.13
      - 4.9.15
      - 4.9.17
      - 4.9.18
      - 4.9.19
      - 4.9.21
      - 4.9.22
      - 4.9.23
      - 4.9.24
      - 4.9.25
      - 4.10.3
      - 4.10.4
      - 4.10.5
