apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-impersonate-cluster-admin
rules:
  - apiGroups:
      - ""
    resources:
      - users
    verbs:
      - impersonate
    resourceNames:
      - backplane-cluster-admin