apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s-openshift-customer-monitoring
  namespace: openshift-customer-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - alertmanager-main
  - alertmanager-main-proxy
  - prometheus-additional-scrape-config
  - prometheus-additional-scrape-config-2
  - prometheus-additional-alertmanager-config
  - alertmanager-instance
  - prometheus-auth-proxy
  - alertmanager-auth-proxy
  verbs:
  - "*"
